### ISSUE TITLE
DpiAware: problem with ControlBox

### ISSUE THREAD

**Issue by KamilSzymborski** [dennismagno/metroframework-modern-ui#97]
https://ibb.co/gVbzkkr

```
static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            SetProcessDPIAware();
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }

        [System.Runtime.InteropServices.DllImport("user32.dll")]
        private static extern bool SetProcessDPIAware();
    }
```

**Comment by dennismagno** [comment]
Is this a suggested fix?

**Comment by KamilSzymborski** [comment]
I know why you ask - I forgot to mention something: the problem occurs when the interface scaling in the system is greater than 100% - then the application scales.

**Comment by KamilSzymborski** [comment]
**SetProcessDpiAware** is the same as **right click -> properties -> compatibility -> change high DPI settings -> high DPI scalling override: application** on exe, or [link](https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms).

**Comment by KamilSzymborski** [comment]
I don't know how to fix it.

**Comment by KamilSzymborski** [comment]
Oh sorry, NOT ALWAYS, in my case it occurs when scaling 150%.

mb.

**Comment by dennismagno** [comment]
Ok let try to replicate the issue based on the information that you provided. Thanks a lot for your findings.

**Comment by KamilSzymborski** [comment]
Good luck!

**Comment by VBHPS** [comment]
within your project select Add new file and add a "application manifest", add the following in the manifest file: 

[add-inside-app-manifest-file.zip](https://github.com/dennismagno/metroframework-modern-ui/files/3638644/add-inside-app-manifest-file.zip)

Then open your project properties, select application tab then go to the manifest section, select your newly created manifest file, close property window and rebuild solution - should fix your problem.

**Comment by KamilSzymborski** [comment]
Still the same at 150% on 13" on Full HD.

This is just one of the ways to enable dpi aware.

**Comment by VBHPS** [comment]
Hi, within the manifest file inside assembly identity node is that the name of your application? if not input the name of your app.exe.

failing that, i'll code up a sample app for all different dpi and upload it here - give me a day or so.

**Comment by KamilSzymborski** [comment]
> Hi, within the manifest file inside assembly identity node is that the name of your application? if not input the name of your app.exe.

Corrected. However, everything worked fine, the application without scaling on my device looks terrible and you can't miss it.

> Try - within form properties select "AutoScaleMode" change from "Font" to "DPI" see if this helps.

I tried.

> failing that, i'll code up a sample app for all different dpi and upload it here - give me a day or so.

I know how to write applications that scale well.

I generally don't use MetroForm because I don't like - I only use components from MetroFramework.

I just wanted to report a bug.

But I appreciate the willingness.

:)

**Comment by KamilSzymborski** [comment]
I fixed it.

Original:
`newButton.Size = new Size(25, 20);`
To (x and y +4):
`newButton.Size = new Size(29, 24);`

![Untitled](https://user-images.githubusercontent.com/42911971/65435975-a8df3c00-de21-11e9-922f-2b340d66f946.png)

There was simply no space for text on the button.

**Comment by KamilSzymborski** [comment]
It's a solution for my 13-inch Full HD laptop. But it will probably be bad again with 12-inch Full HD etc.
Maybe you need to provide a picture instead of button text.

**Comment by KamilSzymborski** [comment]
And it would be good to add scaling options to MetroForm.

```
if (Environment.OSVersion.Version.Major >= 6) SetProcessDPIAware();
```


```
[DllImport("user32.dll")]
private static extern bool SetProcessDPIAware();
```

**Comment by aceofspades0494** [comment]
@KamilSzymborski I still do not understand how you were able to fix the maximize and minimize boxes in the Control Box using DPI Aware. Could you elaborate on how you fixed that?

**Comment by KamilSzymborski** [comment]
I finally fixed it by implementing auto scaling.

```csharp
float dpi;

using (var g = newButton.CreateGraphics())
      dpi = (96 - Math.Max(g.DpiX, g.DpiY));

var oldButtonSize = newButton.Size;

var newButtonWidth = Convert.ToInt32(oldButtonSize.Width + (oldButtonSize.Width * dpi));
var newButtonHeight = Convert.ToInt32(oldButtonSize.Height + (oldButtonSize.Height * dpi));

newButton.Size = new Size(newButtonWidth, newButtonHeight);
```

I am sending you MetroForm.cs - just swap it.

(_MetroFramework/Forms/MetroForm.cs_).

[MetroForm.zip](https://github.com/dennismagno/metroframework-modern-ui/files/6014202/MetroForm.zip)

**Comment by KamilSzymborski** [comment]
Finally I solved this by implementing auto-scaling to the window buttons.

```csharp
float dpi;

using (var g = newButton.CreateGraphics())
    // 96 is base /default DPI, is like 100% system scaling
    dpi = (96 / Math.Max(g.DpiX, g.DpiY)); 

var oldButtonSize = newButton.Size;

var newButtonWidth = Convert.ToInt32(oldButtonSize.Width + (oldButtonSize.Width * dpi));
var newButtonHeight = Convert.ToInt32(oldButtonSize.Height + (oldButtonSize.Height * dpi));

newButton.Size = new Size(newButtonWidth, newButtonHeight);
```

I am sending you _MetroForm.cs_ - replace it in _MetroFramework/Forms_.

[MetroForm.zip](https://github.com/dennismagno/metroframework-modern-ui/files/6014224/MetroForm.zip)

**Comment by aceofspades0494** [comment]
Kamil,

Thank you very much!!! I can't express my gratitude enough, this really
helped with the issue I was dealing with.
